name: Lint GitHub Actions

on:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/*.ya?ml'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/*.ya?ml'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Run actionlint"
        uses: raven-actions/actionlint@v2
        with:
          matcher: true
          cache: false
          fail-on-error: false
